# Generated by Django 5.2.4 on 2025-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
