# Generated by Django 5.2.4 on 2025-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodItems', '0002_fooditem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(upload_to='food-images/'),
        ),
    ]
