# Generated by Django 5.2.4 on 2025-08-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebaseUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
