# Generated by Django 5.2.4 on 2025-09-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='gateaway_response',
            new_name='gateway_response',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currancy',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='val_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='num_of_items',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='INITIATED', max_length=20),
        ),
    ]
