# Generated by Django 5.2.4 on 2025-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pament', '0002_rename_gateaway_response_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='num_of_items',
            field=models.IntegerField(max_length=10),
        ),
    ]
